### ISSUE TITLE
[Feature] Privacy Manifest: UserDefaults

### ISSUE THREAD

**Issue by LFMAKER** [castle/castle-react-native#109]
Apple is recommending declaring the use of the UserDefaults API in the privacy manifest file.
https://developer.apple.com/news/?id=r1henawx

**Describe the solution you'd like**
Create a privacy manifest declaring all APIs and reasons.

**Additional context**
```
Used symbols in binary ./Castle/libCastle.a: NSUserDefaults
```

UserDefault API: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401

**Comment by aalekz** [comment]
Hi @LFMAKER!

Thanks for pointing this out, we're working on adding the privacy manifest file to the library and will be publishing a new version in the coming weeks.

**Comment by aalekz** [comment]
Hi @LFMAKER,

We've implemented the soon to be required privacy manifest file in our underlaying SDK. Version 2.0.13 of this now supports the new privacy manifest.

Please let me now if there is anything else I can help you with in the future, closing the issue as completed :)

**Comment by LFMAKER** [comment]
@aalekz Thanks for the update! Everything's set up and the Privacy Manifest looks good. Appreciate it! 🎉
